#!/usr/bin/env python2.7
# A test harness for the Dealer's step4 method

import sys
import json
from dealer.playerState import *
from dealer.species import *
from dealer.action4 import *

try:
	testInput = json.load(sys.stdin)
	if len(testInput) == 3:
		ps = PlayerState.playerStateFromJson(testInput[0])
		befores = [[Species.speciesFromJson(specJson) for specJson in specList] for specList in testInput[1]]
		afters = [[Species.speciesFromJson(specJson) for specJson in specList] for specList in testInput[2]]
		action = ps.player.choose(befores, afters)
		print json.dumps(Action4.actionToJson(action))

except Exception as e:
#	raise e
	quit()
