#!/usr/bin/env python2.7
# CREATES PLAYERS
import sys
import socket
from client.proxyDealer import ProxyDealer
from client.sillyPlayer import SillyPlayer

HOST_IP = "127.0.0.1"
HOST_PORT = 56789
TIMEOUT = 30

"""
	Create a socket for the given player and wait for an "ok" message from the server
	Player -> Socket or False
"""
def register(player):
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sock.settimeout(TIMEOUT)
	sock.connect((HOST_IP, HOST_PORT))
	sock.sendall("ping")
	message = sock.recv(1024)
	if message == "ok":
		return sock
	else:
		return False

"""
	Create a ProxyPlayer with our strategy and connect to the server
	Nat -> Void
"""
def main(numPlayers):
	player = SillyPlayer()
	resp = register(player)
	if resp is not False:
		dealerProxy = ProxyDealer(player, resp)
	else:
		print "Failed to connect to server at IP {}/port {}!".format(HOST_IP, HOST_PORT)
		quit()

if __name__ == "__main__":
	main(1)
