#!/usr/bin/env python2.7
import sys
import socket
from server.dealer import *
from server.playerState import PlayerState
from server.proxyPlayer import ProxyPlayer
import time

HOST_IP = "127.0.0.1"
HOST_PORT = 56789
TIMEOUT = 30

"""
	Create a socket and bind to the global port
	Void -> Socket
"""
def setUpSock():
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sock.bind((HOST_IP, HOST_PORT))
	sock.listen(1)
	sock.settimeout(TIMEOUT)
	return sock

"""
	Create a server that supports the given number of players
	Then, wait for enough players to connect and run a game
	Nat -> Void
"""
def main(numPlayers):
	sock = setUpSock()
	players = []
	while len(players) < numPlayers: # TODO: time out when we haven't received enough players in a reasonable amt of time
		conn, addr = sock.accept()
		ping = conn.recv(512)
		conn.sendall("ok")
		player = PlayerState(len(players) + 1, 0, [], [], ProxyPlayer(conn))
		players.append(player) 

	time.sleep(1)
	deal = Dealer(players, 0)
	deal.runGame()


if __name__ == "__main__":
	if len(sys.argv) > 1 and int(sys.argv[1]) >= 3 and int(sys.argv[1]) <= 8:
		main(int(sys.argv[1]))
	else:
		print "Usage: ./main-server N where N is the number of players for this game"
		print "Number of players must be between 3 and 8 inclusive"
		quit()
