#!/usr/bin/env python2.7
import sys
import socket
from server.dealer import *
from server.playerState import PlayerState
from server.proxyPlayer import ProxyPlayer

HOST_IP = "127.0.0.1"
HOST_PORT = 56789
TIMEOUT = 30

def setUpSock():
	sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sock.bind((HOST_IP, HOST_PORT))
	sock.listen(1)
	sock.settimeout(TIMEOUT)
	return sock

def main(numPlayers):
	sock = setUpSock()
	players = []
	while len(players) < numPlayers: # TODO: time out when we haven't received enough players in a reasonable amt of time
		conn, addr = sock.accept()
		ping = conn.recv(512)
		conn.sendall("ok")
		player = PlayerState(len(players) + 1, 0, [], [], ProxyPlayer(conn))
		players.append(player) 

	deal = Dealer(players, 0)
	deal.runGame()


if __name__ == "__main__":
	numPlayers = int(sys.argv[1])
	if numPlayers >= 3 and numPlayers <= 8:
		main(numPlayers)
	else:
		print "Number of players must be between 3 and 8 inclusive"
		quit()
